compucorp/webform_civicrm_membership_extras

webform_civicrm_membership_extras.module

I was calling  : 
**wf_crm_webform_postprocess::singleton($node)**
which only work if the webform is a civicrm-enabled wbform which causes fatal error when submitting a non civicrm-enabled webform.
And because we only need this module to work if the webform is civicrm-enabled, I've added an extra check to ensure that the module only work for civicrm-enabled webforms.

BASW-155: Make sure that the module work only on civicrm webform

---

includes/wf_me_discount_code_validator.inc

Cividiscount was integrated with webform in #2 but there is an issue with using discount code with usage limit set, as the error `Discount code usage exceeded.` is always displayed.
There was an error in the validation logic which was always checking of the maximum usage number is greater or equal to the number of times the discount code has been used, the fix was to reverse this condition.

BASW-392: Fix error with discount code usage limit.

---

webform_civicrm_membership_extras.install

**webform_discount_settings**  was only getting creating when upgrading the module but not when installing it, this PR fixes that so the table get both created upon upgrade or installation.

RSE-78: Create webform_discount_settings table on installation

---

webform_civicrm_membership_extras.module

The issue originally appeared and fixed  in the prospect extension here : https://github.com/compucorp/uk.co.compucorp.civicrm.prospect/pull/44
implementing apiWrappers hook 2nd argument **$apiRequest** for v3 calls except an array where for v4 expect an object which might cause issues depending on the implementation of the hook.
If the **$apiRequest** is an object then it means it is an API v4 call and then we return early

MAE-153: Prevent executing apiWrappers hook for API v4

---

webform_civicrm_membership_extras.module

When editing webform  the ‘apply discount’ field is automatically added into the list of webform components every time a webform is saved even the Discounts integration is not enabled. 
Field 'apply discount' is always created when webform is saved.
Field 'apply discount' is only created when Discount Enabled is ticked.

BASWSPRT-74: Fixed 'Apply discount' field is automatically added to webform component

---

webform_civicrm_membership_extras.module

Submitting a webform that is configured to create an auto-renewed membership(s) is not creating the recur line items (the records in membership_subscription_lines table) which result in having empty screen when visiting "manage installments" on CiviCRM
Doing the above will create the recur line items and "manage installments" page contain line items on both current and next period tabs : 
This was done by updating webform_civicrm_membership_extras_webform_submission_insert() hook which runs after submitting the webform to to call CRM_MembershipExtras_Hook_PostProcess_RecurringContributionLineItemCreator::create() which handle the creation of the recur line items for the recur contribution.

CGP-1508: Populate Recur line items when adding an auto-renewed membership(s)

---

includes/wf_me_cividiscount_ext_helper.inc

When trying to signup new membership using Webform and after applying discount count code, getting 'AJAX HTTP Result code: 500' and unable to create membership with discount.
Fatal error was being thrown when trying to apply discount code as CiviCRM was not initialized and a call to civicrm_api3() method triggered a "Call to undefined function" exception.
Initialized CiviCRM on class constructor.

BASWSPRT-73: Fix Applying Discount Code to Membership Contribution

---

webform_civicrm_membership_extras.module

If you submitted a webform that is configured with multi-memberships where only some of then are configured to be auto-renewed, then in manage installments screen all of them will appear to be an auto-renewal memberships and just the ones you configured to be auto-renewal. Even add-on contributions will appear as auto-renew though auto-renewal for add-on contribution is not supported on webforms.
The issue happen because the membershipextras extension always set the auto_renew flag on the recur contribution line items to TRUE without looking if the membership is an auto-renewal membership or not, I changed this in this PR so the auto_renew flag on the recur line item get calculated and set based if the membership is an auto-renewal membership or not. 
I achieved that by creating a new …

MAE-175: Ensure that the auto-renew flag is set correctly after webform submission

---

webform_civicrm_membership_extras.module

When fields are being removed from a webform, a confirmation message is shown asking the user to verify he in fact wants to remove those fields. This screen is showing the 'enable discounts' checkbox, when it shouldn't. Furthermore, when user accepts to remove the fields, an error is shown.
> DOException: SQLSTATE[23000]: Integrity constraint violation: 1048 
Column 'nid' cannot be null: INSERT INTO {webform_discount_settings} (nid, enabled) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1); Array
( [:db_insert_placeholder_0] => [:db_insert_placeholder_1] => 0 ) in wf_me_discount_settings->create() (line 58 of
The screen to show the confirmation message when removing fields is actually the same form as the one where you configure what CiviCRM fields you want to add to a webform, …

MAE-186: Fix Error When Removing Fields From Webform

---

includes/wf_me_discount_amount_helper.inc
webform_civicrm_membership_extras.module

Discounted price is not shown on Contribution page, if membership is created using webform with Payment plan. 
Here Membership fee for Standard is £50 and including tax is £60
a) Membership Signup- 2 Installments-50% Discount is applied
Contribution Screen: Discounted price is not shown, instead original price without 50% discount tax is displayed. It should be £15.00 for 2 installments.
Discounted price was being multiplied by number of installments and stored to session, so that then when calculating the price of each installment the system would take this price stored in session and divide it by the number of installments. Thus, the full discounted prices was being used for each installment, instead of it being divided among all installments. On 50% discount, and 2 installments, the …

BASWSPRT-125: Fix Contribution Amounts When Applying Discounts

---

README.md

We need to document the patches required for the membership extras module to work.
There was no documentation of the patches required for the module to work.
Added documentation on the patches we're maintaining on CiviCRM Webforms Drupal module.
This shows the current state of the readme:
https://github.com/compucorp/webform_civicrm_membership_extras/blob/MAE-262-update-readme-with-patches-required/README.md

MAE-262: Update Readme With Description of Required Patches

---

webform_civicrm_membership_extras.info

Bumping version to 7.x-4.0 as part of Membershipextras suite version 4.0.0 release.

MAE-411: Bump version to 7.x-4.0

---

includes/wf_me_discount_settings.inc

Saving a webform results in an error.
- Create a new webform
- Go to Civicrm tab
- Check Enable Civicrm Processsing
- Click on “Save Settings”
- Error is thrown
There is a query used by wf_me_discount_settings class to determine if there are any settings stored in the discount settings table (webform_discount_settings). The query is built using Drupal's core DB management classes, but they were being used wrongly. Specifically, the call to the `SelectQuery::fields()` expects two parameters, the table alias, and an array of field names. We were only passing one parameter, the name of the field we expected to be returned.
https://git.drupalcode.org/project/drupal/-/blob/7.x/includes/database/select.inc#L1316-1330
Made the call to `SelectQuery::fields()`, passing both table alias and array …

CPS-422: Fix Query Built to Count Cividiscount Settings

---

webform_civicrm_membership_extras.module

This is a continuation of the work that is done here: https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/355
it basically ensures that the "Is active" field is set correctly when creating or renewing payment plan membership using webforms using the API created in the above PR.

MAE-477: Manage payment plan active status on webform submission

---

webform_civicrm_membership_extras.module

This PR adds a hook that is dispatched before creating the payment plan remaining upfront installments, which allows other modules to alter any data needed before creating the rest of the installments.
The main reason for creating it is to allow the "webform-manualdd" to attach the mandate to the payment plan and to the installments, and to allow altering the dates for the payment plan and the first installment in case a direct debit payment was made, more info can be found in this PR: https://github.com/compucorp/webform-manualdd/pull/24

BASW-756: Add hook to allow changing things before creating upfront installments

---

includes/wf_me_prorated_billing_apiwrapper.inc
webform_civicrm_membership_extras.info
webform_civicrm_membership_extras.module

This PR adds pro rata calculations to fixed membership line items.
If there is a discount code applied
First, the [ca55546](https://github.com/compucorp/webform_civicrm_membership_extras/pull/36/commits/ca55546f179a20dd9bc7849d2de81235bf7237d7) commit checks the following rules before applying the pro rata calculations :
- Memberships are of duration type "fixed".
- Number of terms to be "1" or "- Enter Dates Manually -"
- Membership fee is not set manually
Second, the [254c56](https://github.com/compucorp/webform_civicrm_membership_extras/commit/254c56919bc58639afd4b7069cccafa873bb9eea) commit updates the prorated membership items by utilizing the validate hook so that we can adjust the line items before the alter_form hook called by …

MAE-554: Add support for pro rata calculations.

---

webform_civicrm_membership_extras.module

This PR sets start date to today for fixed membership line items.
This PR uses the webforms' validation hook to create a new webform component for each selected membership type by updating the `$form['#node']->webform['components']` array. and to create the corresponding submitted value.
If the webform is configured to allow the user to set the start date then we skip updating the webform. Lastly, this only happens during the last submission.

MAE-573: Set start date of prorated memberships

---

webform_civicrm_membership_extras.module

This PR sets the number of terms to 1 for memberships with manually entered dates.
If we choose to enter dates manually, we have to add the membership fee field to provide the price. Otherwise the membership will be free according to the default behaviour of webform_civicrm.
We don't want to enable the membership fee field so that default membership fee from CiviCRM membership type settings will be loaded. But if we didn't create the membership will be free and no contribution will be created.
After the investigation, I found that `webform_civicrm` sets the `num_terms` to 0 for manually entered dates memberships so the quantity and the total price of the line item will be zero here at [wf_crm_webform_postprocess.inc#L1572](https://github.com/colemanw/webform_civicrm/blob/7.x-4.x/includes/w …

MAE-575: Memberships with manually entered dates

---

webform_civicrm_membership_extras.module

Drupal webform allows the user to add fieldset to group multiple fields together which makes the submitted array structure nested and our code not working. This PR updates the code to properly access nested elements using the `RecursiveIteratorIterator`.
https://user-images.githubusercontent.com/74309109/133969566-c54a1b6a-542e-4f80-841d-737df502d127.mp4
https://user-images.githubusercontent.com/74309109/133969373-f430811f-13f2-4f36-9ea7-d77460a480da.mp4
Look at the below example of the submitted values.
```php
$form_state['input']['submitted'] = [
'civicrm_1_contact_1_fieldset_fieldset' => [
'civicrm_1_contact_1_contact_first_name' => 'Bruce',
'civicrm_1_contact_1_contact_last_name' => 'Wayne',
'civicrm_1_contact_1_contact_last_name' => 'Wayne',
'main_membership' => [ …
```

MAE-575: Handle nested webform fields

---

webform_civicrm_membership_extras.module

This PR fixes an issue that prevents the prorated calculation if the membership select page was the last.
The confirmation page shows the full price.
https://user-images.githubusercontent.com/74309109/143025653-98377069-52bb-4751-bb55-f5a12fcee961.mp4
The confirmation page shows the prorated price.
https://user-images.githubusercontent.com/74309109/143025227-125703d7-70e4-4891-b26b-b06dadd62227.mp4
The `webfrom_civicrm` module uses the `$form['#validate']` array to do the payment by adding a callback and the `webform` module will call those callbacks stored in the `$form['#validate']` array. We have to do the same and add our callback to  `$form['#validate']` array.
The function `_webform_civicrm_membership_extras_is_prorated_billing_enabled` checks the form whether prorated calculation …

IO-341: Fix the prorated calculation if the membership select page was the last

---

.github/PULL_REQUEST_TEMPLATE.md
js/webform_civicrm_membership_extras.js
webform_civicrm_membership_extras.module

In this PR we resolve the issue with the `discount apply button` being separated from the `discount code input field` or not displayed on the screen.
`On client A`
`On client B`
`Compuclient`
We tried grouping the discount fields together using fieldsets, but this didn't work. we opted for a JS solution to move the fields into the fieldset.

BASW-923: Group discount fields together

---

webform_civicrm_membership_extras.module

In this PR we resolve the issue with an error being displayed when clicking `Save Draft` on the Preview page of webforms
This error happens because the `$form_state['input']['submitted']` array is NULL when the formed is saved as a draft, and RecursiveArrayIterator class expects an array. https://github.com/compucorp/webform_civicrm_membership_extras/blob/162210f2d86c4c83e30643b2cfc97b45a116d882/webform_civicrm_membership_extras.module#L903
To resolve the error we added a check at the top of the function, so it returns immediately if the form is being saved as a draft i.e. `$form_state['input']['submitted']` is empty.

EF-52: Ensure submitted field is not empty

---

webform_civicrm_membership_extras.module

If you have a webform configured with the following:
- Fixed membership
- The number of terms = "Enter Dates Manually"
- With Either Start or End Date or both ticked
- And with either Start or End Date or both set as "Private" or "Hidden" field with a default value
Then the pro-rata calculation will not respect the start or the end date that are configured as default values on the webform.
e.g 
Here is an example webform that is configured with one fixed membership and private end date with the default value = "2023-12-21":
The fixed membership type that is used in the above webform has the end date of "31 December" with annual Fee = $100
so the fee of single day in non leap year is: $100/365 = $0.273972603
If I submit the webform above at  "2023-12-14", then it should do the pro-rata for …

ESEB-113: Respect private and hidden membership start and end dates during pro-rata calculation

---

webform_civicrm_membership_extras.module

When renewing an active (membership status with "is current" = True) fixed  memberships using webforms, the pro-rata are getting applied on membership fees instead of using the full membership fees:
https://github.com/compucorp/webform_civicrm_membership_extras/assets/6275540/b401fc5d-5c4e-4fbb-b234-527e696408ff
When renewing an active (membership status with "is current" = True)  fixed  memberships using webforms, the full membership price is applied:
https://github.com/compucorp/webform_civicrm_membership_extras/assets/6275540/c3285086-2e27-4bfe-9f20-25ea43676c54
The pro-rata calculation relies on the submitted membership dates to calculate the fee, and if not supplied, which is the case when doing renewal, then it will use today's date as start date by default when doing the …

PROD-165: Use the full fixed membership fee on renewal without any pro-rata

---

webform_civicrm_membership_extras.module

After this PR: https://github.com/compucorp/webform_civicrm_membership_extras/pull/62
the pro-rata calculation seems to happen just fine while going through webform pages, but once the webform is submitted, the contribution that is created will be have the full membership price instead of the pro-rata amount that showed up before submitting the webform.
https://github.com/compucorp/webform_civicrm_membership_extras/assets/6275540/09043fbf-9516-4f77-883e-dc6e256a16f4
https://github.com/compucorp/webform_civicrm_membership_extras/assets/6275540/408b32c0-b487-4550-8fd2-4648076f3802
I made a typo in previous PR where I introduced new array key inside the membership types array called `type_data`, but then in one location I wrote `type_id` instead, so I changed it back to `type_data`,

PROD-165: Fix pro-rata calculation regression caused by PROD-165 work
